#!/usr/bin/env python3
"""Generate firmware/src/led_map.h from busradar-schema.sql.

The SQL file's INSERT order matches the routes.id SERIAL values, which in
turn correspond to the physical LED indices. Points with index >= LED_COUNT
are off-map route points used only for nearest-neighbour snapping.
"""
import re
import sys
from pathlib import Path

LED_COUNT = 65

ROOT = Path(__file__).resolve().parents[2]
SQL = ROOT / "busradar-schema.sql"
OUT = ROOT / "firmware" / "src" / "led_map.h"

POINT_RE = re.compile(r"POINT\(\s*([0-9.+-]+)\s+([0-9.+-]+)\s*\)")


def main() -> int:
    text = SQL.read_text()
    matches = POINT_RE.findall(text)
    if not matches:
        print(f"no POINT() entries found in {SQL}", file=sys.stderr)
        return 1

    lons = [float(lon) for lon, _ in matches]
    lats = [float(lat) for _, lat in matches]
    n = len(lons)

    lines = [
        "// Auto-generated by firmware/scripts/gen_led_map.py",
        "// Do not edit by hand. Regenerate after changing busradar-schema.sql.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        f"constexpr size_t ROUTE_COUNT = {n};",
        f"constexpr size_t LED_COUNT  = {LED_COUNT};",
        "",
        f"constexpr float ROUTE_LON[ROUTE_COUNT] = {{",
    ]
    for lon in lons:
        lines.append(f"    {lon:.10f}f,")
    lines.append("};")
    lines.append("")
    lines.append("constexpr float ROUTE_LAT[ROUTE_COUNT] = {")
    for lat in lats:
        lines.append(f"    {lat:.10f}f,")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({n} points, LED_COUNT={LED_COUNT})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
