[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7
    adafruit/Adafruit NeoPixel@^1.12
build_flags = -std=gnu++17

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
